services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homehub.stream,www.homehub.stream,158.179.194.143:37620,127.0.0.1:37620
    ports:
      - 37620:3000
    volumes:
      - ./config:/app/config
    restart: unless-stopped
