# 家庭服务器服务目录 (homehub.stream) - 统一 HTTPS + 8443 + 反向代理
# 更多参数配置，请参考官方文档：https://gethomepage.dev/configs/services/
# 对于小组件（Widgets）的详细配置，请参考：https://gethomepage.dev/configs/widgets/

- 核心系统:
      - 飞牛OS:
            icon: mdi-server
            href: https://h-fn.homehub.stream:8443
            description: 飞牛OS - 宿主机管理面板
            target: _blank # 在新标签页中打开
            ping: https://h-fn.homehub.stream:8443 # 添加服务状态检测
            # server: my-docker-server # 如果通过 Docker API 连接，请指定服务器
            # container_name: feiniu-os # 如果是 Docker 容器，可以指定容器名以显示状态

      - 飞牛影视:
            icon: mdi-movie-play-outline
            href: https://h-fn.homehub.stream:8443/v
            description: 飞牛影视 - Jellyfin 或 Emby 服务
            target: _blank
            ping: https://h-fn.homehub.stream:8443/v
            # widget: # 示例：如果支持，可以添加Jellyfin/Emby小组件显示最近添加等
            #   type: jellyfin # 或 emby
            #   url: https://h-fn.homehub.stream:8443/v
            #   key: YOUR_API_KEY

- 下载工具:
      - qBittorrent:
            icon: mdi-download
            href: https://h-qbt.homehub.stream:8443
            description: qBittorrent 下载工具 WebUI
            target: _blank
            ping: https://h-qbt.homehub.stream:8443
            # widget: # qBittorrent 小组件示例 (需要填写您的qBittorrent实际配置)
            #   type: qbittorrent
            #   url: https://h-qbt.homehub.stream:8443
            #   username: your_username
            #   password: your_password
            #   fields: ["status", "speed", "eta", "progress"] # 可选显示字段

      - Transmission:
            icon: mdi-progress-download
            href: https://h-tr.homehub.stream:8443
            description: Transmission Web 控制台
            target: _blank
            ping: https://h-tr.homehub.stream:8443
            # widget: # Transmission 小组件示例 (需要填写您的Transmission实际RPC配置)
            #   type: transmission
            #   url: https://h-tr.homehub.stream:8443 # 通常是RPC地址，如 http://localhost:9091/transmission/rpc
            #   username: your_rpc_username # 如果设置了RPC认证
            #   password: your_rpc_password # 如果设置了RPC认证
            #   fields: ["status", "speed", "eta", "progress"] # 可选显示字段

- 虚拟化与运维:
      - Proxmox VE:
            icon: mdi-virtual-reality
            href: https://h-pve.homehub.stream:8443
            description: PVE 虚拟化管理平台
            target: _blank
            ping: https://h-pve.homehub.stream:8443
            # widget: # Proxmox VE 小组件示例 (具体参数请查阅文档)
            #   type: proxmox
            #   url: https://h-pve.homehub.stream:8443
            #   username: your_pve_username@pam # 或 @pve
            #   token_name: your_api_token_name
            #   token_value: your_api_token_value
            #   fields: ["vms", "lxc", "storage", "nodes"] # 可选显示字段

      - 1Panel:
            icon: mdi-monitor-dashboard
            href: https://h-1p.homehub.stream:8443
            description: 现代化服务器管理面板
            target: _blank
            ping: https://h-1p.homehub.stream:8443

      - 青龙面板:
            icon: mdi-robot-outline
            href: https://h-ql.homehub.stream:8443
            description: 青龙面板 - 定时任务管理
            target: _blank
            ping: https://h-ql.homehub.stream:8443

- 常用PT站:
      - 馒头 (M-Team):
            icon: mdi-nas
            href: https://kp.m-team.cc/
            description: 中文综合 PT 大站，以高清影视资源为主
            target: _blank # 外部链接建议在新标签页打开
            # ping: https://kp.m-team.cc/ # 可以添加，但外部站点状态不由您控制

      - 海豚音乐 (DICMusic):
            icon: mdi-music-note
            href: https://dicmusic.com/
            description: 专注高质量音乐资源的PT站
            target: _blank

      - CarPT:
            icon: mdi-car
            href: https://carpt.net/
            description: 车PT或小车（CarPT） 影视 / 音乐资源
            target: _blank

      - PTSKit:
            icon: mdi-tools
            href: https://www.ptskit.com/
            description: PTS 短剧站
            target: _blank

- 网络工具:
      - DDNS-Go:
            icon: mdi-dns
            href: https://h-ddns.homehub.stream:8443
            description: 动态 DNS 自动更新服务
            target: _blank
            ping: https://h-ddns.homehub.stream:8443
