---
# 家庭服务器服务目录 (homehub.stream) - 统一 HTTPS + 8443 + 反向代理
- 核心系统:
      - 飞牛OS:
            icon: mdi-server
            href: https://h-fn.homehub.stream:8443
            description: 飞牛OS
      - 飞牛影视:
            icon: mdi-movie-play-outline
            href: https://h-fn.homehub.stream:8443/v
            description: 飞牛影视

- 下载工具:
      - qBittorrent:
            icon: mdi-download
            href: https://h-qbt.homehub.stream:8443
            description: qBittorrent 下载工具 WebUI
      - Transmission:
            icon: mdi-progress-download
            href: https://h-tr.homehub.stream:8443
            description: Transmission Web 控制台

- 虚拟化与运维:
      - Proxmox VE:
            icon: mdi-virtual-reality
            href: https://h-pve.homehub.stream:8443
            description: PVE 虚拟化管理平台
      - 1Panel:
            icon: mdi-monitor-dashboard
            href: https://h-1p.homehub.stream:8443
            description: 现代化服务器管理面板
      - 青龙面板:
            icon: mdi-robot-outline
            href: https://h-ql.homehub.stream:8443
            description: 青龙面板
- 常用PT站:
      - 馒头 (M-Team):
            icon: mdi-nas
            href: https://kp.m-team.cc/
            description: 中文综合 PT 大站，以高清影视资源为主
      - 海豚音乐 (DICMusic):
            icon: mdi-music-note
            href: https://dicmusic.com/
            description: 专注高质量音乐资源的PT站
      - CarPT:
            icon: mdi-car
            href: https://carpt.net/
            description: 车PT或小车（CarPT） 影视 / 音乐资源
      - PTSKit:
            icon: mdi-tools
            href: https://www.ptskit.com/
            description: PTS 短剧站

- 网络工具:
      - DDNS-Go:
            icon: mdi-dns
            href: https://h-ddns.homehub.stream:8443
            description: 动态 DNS 自动更新服务
