# Homepage 设置配置文件
# 更多信息请参考官方文档: https://gethomepage.dev/latest/configs/settings/

title: 极客任意门 - GeekBase
shortTitle: GeekBase
favicon: https://magichub.top/download/static/GeekBase/favicon.ico

headerStyle: boxedWidgets # 头部样式，可选值: default (默认), underlined (下划线), boxed (盒子), clean (简洁), boxedWidgets (小部件盒子)
theme: dark
color: slate # 颜色主题，具体取决于您选择的主题，常见有: slate (石板色), sky (天空蓝), amber (琥珀色), rose (玫瑰色) 等

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # 背景模糊程度: none (无), sm (小), md (中), lg (大), xl (极大)
  saturate: 100 # 背景饱和度 (0-200，100为原始值)
  brightness: 80 # 背景亮度 (0-200，100为原始值)
  opacity: 70 # 背景图片叠加在主题背景色上的不透明度 (0-100)

fullWidth: true # 内容是否撑满整个页面宽度
useEqualHeightCards: true # 服务卡片是否等高显示

layout: # 服务组布局配置
  # 您可以在这里定义服务组的布局、顺序和图标
  # 服务组的名称需要与您在 services.yaml (或其他服务定义文件) 中的组名完全对应
  "个人常用链接": # 这是您在 services.yaml 中定义的组名
    style: row # 排列方式: row (行) 或 column (列)
    columns: 4 # 每行显示的卡片数量 (当 style 为 row 时生效)
    icon: mdi-link-variant # 图标，来自 Material Design Icons (mdi-) 或 Simple Icons (si-)
    # order: 1 # 可选，用于手动排序，数字越小越靠前

  "家庭服务":
    style: row
    columns: 3
    icon: mdi-home-assistant
    # order: 2

  "NAS & 存储":
    style: row
    columns: 3
    icon: mdi-nas
    # order: 3

  "域名与网络管理":
    style: row
    columns: 3
    icon: mdi-dns
    # order: 4

  "其他服务": # 预留一个通用分组
    style: column
    columns: 1 # 当 style 为 column 时，通常设置为 1
    icon: mdi-dots-horizontal
    # order: 5

# 如果您有天气或其他需要API密钥的服务提供商，可以在这里配置
providers:
  openweathermap: b79ccd07da22a1684b055550a478cf0f
#   weatherapi: YOUR_WEATHERAPI_KEY # WeatherAPI API密钥

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google

# 默认链接打开方式:
# _self: 在当前标签页打开
# _blank: 在新标签页打开
# _parent: 在父框架中打开
# _top: 在整个窗口中打开
target: _blank
# 其他可选设置
hideVersion: true # 是否隐藏页面底部的 Homepage 版本信息
showStats: true # 如果服务支持并且已配置，是否在状态点旁显示简要统计信息
statusStyle: "icon" # 服务状态点的样式: "dot" (圆点) 或 "icon" (基于图标颜色变化)
