---
# 书签
# 参考文档：https://gethomepage.dev/configs/bookmarks/

- 搜索:
    - GitHub:
        - abbr: GHS
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github.png
          href: https://github.com/search?type=Repositories&q=
          description: 代码仓库搜索
    - V2EX:
        - abbr: V2S
          icon: /icons/v2ex.png
          href: https://www.sov2ex.com/?q=
          description: 技术社区搜索

- 人工智能:
    - ChatGPT:
        - abbr: GPT
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/openai.png
          href: https://chatgpt.com/
          description: AI聊天助手

- 开发网站:
    - GitHub:
        - abbr: GH
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github-light.png
          href: https://github.com/
          description: 代码托管平台

- 社交论坛:
    - Reddit:
        - abbr: RE
          icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/reddit.png
          href: https://reddit.com/
          description: 全球社区论坛
    - V2EX:
        - abbr: V2EX
          icon: /icons/v2ex.png
          href: https://www.v2ex.com/
          description: 中文技术社区

- 资源:
    - 猫狸盘搜:
        - abbr: ML
          href: https://www.alipansou.com/
          description: 阿里云盘资源搜索
          target: _blank
    - 阿里小站:
        - abbr: AL
          href: https://pan666.net/
          description: 阿里云盘资源论坛
          target: _blank
    - ZLibrary:
        - abbr: ZL
          icon: /icons/zlibrary.png
          href: https://zh.z-library.gs/
          description: 全球电子书库
          target: _blank

- 工具:
    - 图片压缩:
        - abbr: TINY
          href: https://tinypng.com/
          description: 图片压缩工具
          target: _blank
    - 虫部落.快搜:
        - abbr: KS
          href: https://search.chongbuluo.com/
          description: 聚合快速搜索
          target: _blank

- PT站:
    - 馒头 (M-Team):
        - abbr: MT
          icon: mdi-nas
          href: https://kp.m-team.cc/
          description: 综合影视PT站
          target: _blank
    - CarPT:
        - abbr: CPT
          icon: mdi-car
          href: https://carpt.net/
          description: 车友影视站
          target: _blank
    - PTS-Kit:
        - abbr: PTK
          icon: mdi-tools
          href: https://www.ptskit.com/
          description: 短剧PT分享
          target: _blank

- 娱乐:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          description: 全球视频平台
    - 实时热榜:
        - abbr: RB
          href: https://momoyu.cc/
          description: 热门榜单
          target: _blank
