# Homepage 设置配置文件
# 官方文档: https://gethomepage.dev/configs/settings/

language: zh-CN
title: 极客任意门 - GeekBase
shortTitle: GeekBase
favicon: https://magichub.top/download/static/GeekBase/favicon.ico

headerStyle: boxedWidgets
theme: dark
color: slate
locale: zh-cn

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  saturate: 100
  brightness: 70
  opacity: 75

fullWidth: false
useEqualHeightCards: true
groupsInitiallyCollapsed: true

layout:
  "search":
    columns: 1

  "NAS服务":
    style: row
    columns: 5
    initiallyCollapsed: false
    icon: mdi-chip
    order: 1

  "运维平台":
    style: row
    columns: 5
    initiallyCollapsed: false
    icon: mdi-server
    order: 2

  "下载工具":
    style: row
    columns: 5
    initiallyCollapsed: true
    icon: mdi-cloud-download
    order: 3

# 天气或其他需要API密钥的服务提供商
providers:
  openweathermap: b79ccd07da22a1684b055550a478cf0f

# 快捷启动 直接输入
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google

# 默认链接打开方式:
target: _blank
hideVersion: true
showStats: true
statusStyle: "dot"
hideErrors: true
