---
# 首页小组件
# 参考：https://gethomepage.dev/widgets/

- search:
    provider: google
    focus: true
    target: _blank
    showSearchSuggestions: true
    id: searchBar

- resources:
    label: 系统
    cpu: true
    memory: true
    disk: /
    cputemp: true
    tempmin: 0
    tempmax: 100
    uptime: true
    units: imperial
    refresh: 3000
    diskUnits: bytes
    network: true

- datetime:
    label: 当前时间
    timezone: Asia/Shanghai
    text_size: xl
    hour12: true
    locale: zh-Hans
    format:
      dateStyle: medium
      timeStyle: short

- openweathermap:
    label: 杭州天气
    latitude: 30.089309
    longitude: 119.932655
    units: metric
    provider: openweathermap
    cache: 5
    locale: zh-Hans
    format:
      maximumFractionDigits: 1
      useGrouping: false

- calendar:
  firstDayInWeek: monday
  view: monthly
  maxEvents: 10
  showTime: true
  timezone: Asia/Shanghai

- freshrss:
  url: https://admin.rsshub.in
  username: astral
  password: Rain@8240
