---
# 首页小组件
# 参考：https://gethomepage.dev/widgets/

#- logo:
#    icon: /icons/icon.png

- search:
    provider: google
    focus: true
    target: _blank
    showSearchSuggestions: true
    id: searchBar

- datetime:
    label: 当前时间
    timezone: Asia/Shanghai
    text_size: xl
    hour12: true
    locale: zh-Hans
    order: 2
    format:
      dateStyle: short
      timeStyle: short

- openweathermap:
    label: 天气
    # latitude: 30.089309
    # longitude: 119.932655
    units: metric
    provider: openweathermap
    cache: 5
    locale: zh-Hans
    order: 3
    format:
      maximumFractionDigits: 1
      useGrouping: false
