---
# 首页小组件
# 参考：https://gethomepage.dev/widgets/

- search:
    provider: google
    focus: true
    target: _blank
    showSearchSuggestions: true
    id: searchBar
    logo:
      href: /icons/logo.png
      target: _blank

# - resources:
#     label: 系统资源
#     cpu: true
#     memory: true
#     cputemp: true
#     tempmin: 0
#     tempmax: 100
#     uptime: true
#     units: imperial
#     refresh: 3000

# - resources:
#     label: 存储与网络
#     disk: /
#     diskUnits: bytes
#     network: true
#     refresh: 3000

- datetime:
    label: 当前时间
    timezone: Asia/Shanghai
    text_size: xl
    hour12: true
    locale: zh-Hans
    order: 2
    format:
      dateStyle: medium
      timeStyle: short

- openweathermap:
    label: 杭州天气
    latitude: 30.089309
    longitude: 119.932655
    units: metric
    provider: openweathermap
    cache: 5
    locale: zh-Hans
    order: 3
    format:
      maximumFractionDigits: 1
      useGrouping: false

- logo:
    icon: /icons/logo.png
